"""Add nullable=False.

Revision ID: 106edda5281c
Revises: d36134524122
Create Date: 2020-11-05 19:55:14.669656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106edda5281c'
down_revision = 'd36134524122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('membership', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('membership', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('room', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('membership', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('membership', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
