"""Remove seen_at, add status.

Revision ID: 36fb2471026c
Revises: 878d8c9db0e2
Create Date: 2020-11-10 17:38:29.165411

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "36fb2471026c"
down_revision = "878d8c9db0e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_seen", sa.Column("status", sa.Boolean(), nullable=False)
    )
    op.drop_column("message_seen", "seen_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_seen",
        sa.Column(
            "seen_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("message_seen", "status")
    # ### end Alembic commands ###
