"""Add nullable=False to room_id in message.

Revision ID: 55575d97157a
Revises: 106edda5281c
Create Date: 2020-11-09 13:51:38.998361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55575d97157a'
down_revision = '106edda5281c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
