"""Rename RoomMembership.

Revision ID: d36134524122
Revises:
Create Date: 2020-11-05 16:48:20.406914

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d36134524122"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "membership",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["room.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("room_membership")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_membership",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("room_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"], ["room.id"], name="room_membership_room_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="room_membership_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="room_membership_pkey"),
    )
    op.drop_table("membership")
    # ### end Alembic commands ###
